main: simpleClient simpleServer

simpleClient: simpleClient.c
	gcc -g -Wall -o simpleClient simpleClient.c

simpleServer: simpleServer.c
	gcc -g -Wall -o simpleServer simpleServer.c

clean:
	rm -f simpleClient simpleServer